import 'package:get/get.dart';

Map<String, Map<String, dynamic>> carTabDataEng = {
  "Chassis": {
    "Body Type": "-",
    "Number of seater": "-",
    "Length": "-",
    "Width": "-",
    "Height": "-",
    "Wheelbase": "-",
    "Front track": "-",
    "Rear track": "-",
    "Ground clearance": "-",
    "Curb weight": "-",
    "Full weight": "-",
    "Capacity": "-",
    "Front/rear axle load": "-",
    "Cargo compartment (Length x Width x Height)": "-",
    "Cargo compartment volume": "-",
    "Min trunk capacity": "-",
    "Max trunk capacity": "-",
    "Loading height": "-",
    "Payload": "-",
    "Trailer load (with brakes)": "-",
  },
  "Gearbox & Handling": {
    "Gearbox & Handling": "-",
    "Gearbox type": "-",
    "Number of speed": "-",
    "Number of gear": "-",
    "Drive wheels": "-",
    "Turning circle": "-"
  },
  "Engine": {
    "Engine type": "-",
    "Engine power": "-",
    "Capacity": "-",
    "Power output": "-",
    "Max power at RPM": "-",
    "Maximum torque": "-",
    "Turnover of maximum torque": "-",
    "Injection type": "-",
    "Boost type": "-",
    "Presence of intercooler": "-",
    "Engine configuration": "-",
    "Number of cylinders": "-",
    "Valves per cylinder": "-",
    "Cylinder bore": "-",
    "Cylinder layout": "-",
    "Stroke cycle": "-",
  },
  "Suspension & Brakes": {
    "Front suspension": "-",
    "Back suspension": "-",
    "Front brakes": "-",
    "Rear brakes": "-"
  },
  "Operating Characteristics": {
    "Max speed": "-",
    "Acceleration (0-100 km/h)": "-",
    "City driving fuel consumption per 100 km": "-",
    "Highway driving fuel consumption per 100 km": "-",
    "Mixed driving fuel consumption per 100 km": "-",
    "Curb weight": "-",
    "Fuel tank capacity": "-",
    "Cruising range": "-",
    "Fuel": "-",
    "Emission standards": "-"
  }
};

Map<String, Map<String, dynamic>> carTabData = {
  "Chassis".tr: {
    "Body type".tr: "-",
    "Number of seater".tr: "-",
    "Length".tr: "-",
    "Width".tr: "-",
    "Height".tr: "-",
    "Wheelbase".tr: "-",
    "Front track".tr: "-",
    "Rear track".tr: "-",
    "Ground clearance".tr: "-",
    "Curb weight".tr: "-",
    "Full weight".tr: "-",
    "Capacity".tr: "-",
    "Front/rear axle load".tr: "-",
    "Cargo compartment (Length x Width x Height)".tr: "-",
    "Cargo compartment volume".tr: "-",
    "Min trunk capacity".tr: "-",
    "Max trunk capacity".tr: "-",
    "Loading height".tr: "-",
    "Payload".tr: "-",
    "Trailer load (with brakes)".tr: "-",
  },
  "Gearbox & Handling".tr: {
    "Gearbox & Handling".tr: "-",
    "Gearbox type".tr: "-",
    "Number of speed".tr: "-",
    "Number of gear".tr: "-",
    "Drive wheels".tr: "-",
    "Turning circle".tr: "-"
  },
  "Engine".tr: {
    "Engine type".tr: "-",
    "Engine power".tr: "-",
    "Capacity".tr: "-",
    "Power output".tr: "-",
    "Max power at RPM".tr: "-",
    "Maximum torque".tr: "-",
    "Turnover of maximum torque".tr: "-",
    "Injection type".tr: "-",
    "Boost type".tr: "-",
    "Presence of intercooler".tr: "-",
    "Engine configuration".tr: "-",
    "Number of cylinders".tr: "-",
    "Valves per cylinder".tr: "-",
    "Cylinder bore".tr: "-",
    "Cylinder layout".tr: "-",
    "Stroke cycle".tr: "-",
  },
  "Suspension & Brakes".tr: {
    "Front suspension".tr: "-",
    "Back suspension".tr: "-",
    "Front brakes".tr: "-",
    "Rear brakes".tr: "-"
  },
  "Operating Characteristics".tr: {
    "Max speed".tr: "-",
    "Acceleration (0-100 km/h)".tr: "-",
    "City driving fuel consumption per 100 km".tr: "-",
    "Highway driving fuel consumption per 100 km".tr: "-",
    "Mixed driving fuel consumption per 100 km".tr: "-",
    "Curb weight".tr: "-",
    "Fuel tank capacity".tr: "-",
    "Cruising range".tr: "-",
    "Fuel".tr: "-",
    "Emission standards".tr: "-"
  }
};
